name: tar_installer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.5.0
  file_picker: ^10.1.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo.png
